//
// Created by Леша on 23.05.15.
//

#ifndef SATELLITE_PROPAGATION_CONSTANTS_H
#define SATELLITE_PROPAGATION_CONSTANTS_H
#include <math.h>
#define SEC_IN_RAD (2 * M_PI) / 1296000
#define RAD_IN_SEC 1296000 / (2 * M_PI)
#endif //SATELLITE_PROPAGATION_CONSTANTS_H